### PR TITLE
Fix performance related pedantic clippy lints

### PR DESCRIPTION
**Pull request by GnomedDev**
This PR enables a couple of lints from the "pedantic" group that can improve performance.

### CODE REVIEW

**Comment by whitequark** [comment]
As far as I can see this is mostly noise. (I'm also personally opposed to use of clippy in general, although opt-in lints are the least bad mode.)

**Comment by whitequark** [comment]
For example, "redundant_else" cannot ever have any impact on performance as it does not change codegen. This is pure overreach with no useful outcome, only churn.

**Comment by GnomedDev** [comment]
Your dismissal and closing without discussion have come across as super hostile to new contributions, you could have just told me to undo said change. I often solve clippy lints to become familiar with a codebase but I'm not going to be looking into this any more.

**Comment by whitequark** [comment]
I feel the same way about your PR; I see it as a statement that boils down to "this codebase isn't to my taste and I would like it to be, without regard to the time of people maintaining it". This is why I responded the way I did. Historically, interactions like this contributed to burnout, so I've decided to make sure I have less of them.

**Pull request closed without merging**
