### PR TITLE
Rename `new` method on Packet types to `new_checked`

### LINKED ISSUE #195: Use new_checked by default
Currently all `Packet` types have at least the two constructor methods `new` and `new_checked`. `new` does no length checks, while `new_checked` obviously does. AFAIK in `std` etc typically the "safe" version is the default and the "unsafe" version is explicitly called with `<name>_unchecked`. Would it make sense to do something like the following?

 1) deprecate `Packet::new_checked`
 2) make `Packet::new` functions do what `Packet::new_checked` does
 3) add `Packet::new_unchecked` functions that do what `Packet::new` does

### PR DESCRIPTION
**Pull request by whitequark**
Fixes #195.

r? @dlrobertson, did I miss anything?

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu try

**Comment by m-labs-homu** [comment]
:hourglass: Trying commit 4be0c8b8fb7c8feb62236e54fb7e69b92937cb2a with merge 077a0dcbc7b26121baaaf8cdd418c03f1e8fb6b6...

**Comment by m-labs-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/402470265?utm_source=github_status&utm_medium=notification)

**Comment by m-labs-homu** [comment]
:hourglass: Trying commit 4be0c8b8fb7c8feb62236e54fb7e69b92937cb2a with merge 87ec5fa59ebc4f8adcc276e3902aae460c4c34c1...

**Comment by m-labs-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/402473724?utm_source=github_status&utm_medium=notification)

**Comment by whitequark** [comment]
@m-labs-homu retry

**Comment by m-labs-homu** [comment]
:hourglass: Trying commit 4be0c8b8fb7c8feb62236e54fb7e69b92937cb2a with merge c13ceef2cf64059440d44192468ab13674690e8d...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/402486802?utm_source=github_status&utm_medium=notification)
State: approved= try=True

**Comment by dlrobertson** [comment]
Looks good! I like how explicit `new_checked` and `new_unchecked` are.

**Comment by whitequark** [comment]
@m-labs-homu r=dlrobertson

**Comment by m-labs-homu** [comment]
:pushpin: Commit 4be0c8b has been approved by `dlrobertson`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 4be0c8b8fb7c8feb62236e54fb7e69b92937cb2a with merge 2a5be8dccf4ea8d021db3f6c9f8e0eac9d481728...

**Comment by whitequark** [comment]
@m-labs-homu r-
Forgot one.

**Comment by whitequark** [comment]
@m-labs-homu r=dlrobertson

**Comment by m-labs-homu** [comment]
:pushpin: Commit 23acdf5 has been approved by `dlrobertson`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 23acdf572d5540ddecb7c20299915c5290bb6907 with merge 72070c952fb6ed61743a82da9b08eb818ff3b2fd...

**Comment by m-labs-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/402491096?utm_source=github_status&utm_medium=notification)

**Comment by whitequark** [comment]
@m-labs-homu retry

**Comment by whitequark** [comment]
@m-labs-homu r=dlrobertson

**Comment by m-labs-homu** [comment]
:pushpin: Commit 9cb7e18 has been approved by `dlrobertson`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 9cb7e1895ad397cd668daa15cf6c7bd8ae417e50 with merge 4d7b43f2fa9336f651038830a824684b69fc2690...

**Comment by m-labs-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/402496796?utm_source=github_status&utm_medium=notification)

**Comment by whitequark** [comment]
@m-labs-homu r=dlrobertson

**Comment by m-labs-homu** [comment]
:pushpin: Commit 680f675 has been approved by `dlrobertson`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 680f6751c9562e2362d56e7e6428e9502c18462b with merge 4a253fecdf21a1eacb33ad38b730c06e26f18d5f...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/402507464?utm_source=github_status&utm_medium=notification)
Approved by: dlrobertson
Pushing 4a253fecdf21a1eacb33ad38b730c06e26f18d5f to master...

**Pull request closed without merging**
