### PR TITLE
Add Clone impl to EthernetFrame

### PR DESCRIPTION
**Pull request by canndrew**

### CODE REVIEW

**Comment by LuoZijun** [comment]
Also add `PartialEq` ?

https://github.com/m-labs/smoltcp/blob/master/src/wire/ipv4.rs#L222

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 0924aa1 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 0924aa1b13e5da8141941ff18e91413f87919268 with merge 1ea5ada5dfd04c74a658f10977b12b885c97b574...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/342130636?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 1ea5ada5dfd04c74a658f10977b12b885c97b574 to master...

**Pull request closed without merging**
