### PR TITLE
Fix icmpv4 check_len

### PR DESCRIPTION
**Pull request by dlrobertson**
- Ensure check_len does not require a packet to be of a certain length
 - Make icmpv4 check_len more similar to icmpv6 check_len

### CODE REVIEW

**Comment by whitequark** [comment]
Hmmm, why wasn't this found by fuzzing?

**Comment by dlrobertson** [comment]
Totally my bad. I just forgot to run it. Maybe it should be added to the ruby script?

**Comment by whitequark** [comment]
> Maybe it should be added to the ruby script?

We can just run it on Travis, something like 30 seconds of fuzzing on each run.

**Comment by dlrobertson** [comment]
:+1: yeah that seems reasonable

**Pull request merged**
