### PR TITLE
Add clippy to CI

### PR DESCRIPTION
**Pull request by dlrobertson**
clippy still throws a lot of warnings, but I'll create a separate meta-bug to look into those.

Fixes: #239

### CODE REVIEW

**Comment by astro** [comment]
looks great to me.

**Comment by dlrobertson** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 3f1a66a has been approved by `dlrobertson`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 3f1a66a02fe1eff2a0c807dc88c3fc7664502b2b with merge bf249333cdfbe026b3d0a8a9fb00e2251c7812d3...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/393930368?utm_source=github_status&utm_medium=notification)
Approved by: dlrobertson
Pushing bf249333cdfbe026b3d0a8a9fb00e2251c7812d3 to master...

**Pull request closed without merging**
