### PR TITLE
Add Packet support for NDISC packet types

### PR DESCRIPTION
**Pull request by dlrobertson**
Add packet layer support for NDISC packet types.

Including adding the `Repr` variants in this PR would
make it quite large. I'll add that in the follow-up PR.

### CODE REVIEW

**Comment by whitequark** [comment]
Thanks for the PR! This looks good to me, but can you extract the packet definitions into `wire/ndisc.rs`, as discussed before? They would still be defined for the same structure, I think `use super::icmpv6::*;` should do the trick visibility wise.

**Comment by dlrobertson** [comment]
Ah, good point. Updated.

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 811a32b has been approved by `whitequark`

**Comment by whitequark** [comment]
@dlrobertson Sorry for the delay!

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 811a32b1f80fd9fabbc2aa47281dd54c4d661a9b with merge 4aeeac09d564378f217131f5adf46c9b72a1fae2...

**Pull request closed without merging**
