### PR TITLE
pcap timestamp bugfix

### LINKED ISSUE #512: Incorrect time format for pcap leads to wierd wireshark graph
This is a tcptrace graph(receiver side) produced by wireshark. Why does it always have a 1-sec gap? 
image

An linux socket is like this
image

### PR DESCRIPTION
**Pull request by JakkuSakura**
fixes #512

### CODE REVIEW

**Review by Dirbaio — APPROVED** [review]
Nice catch! Thank you

**Comment by JakkuSakura** [comment]
Consider use `microsecond` as internal unit?

**Comment by Dirbaio** [comment]
~Instant is in ms because with us it'd overflow after aprox 70 minutes, which might be too short for some use cases. Sometimes you want TCP timeouts in the order of hours.~

Edit: they're in u64 so no, they wouldn't overflow that fast. Maybe!

**Comment by JakkuSakura** [comment]
> Edit: they're in u64 so no, they wouldn't overflow that fast. Maybe!

I'm using nanoseconds in i64 in my program, and it will overflow after 292 years since 1970. us would give you 292471 years.

I would like to file a PR on it.

**Pull request merged**
