### PR TITLE
Send multicast to the right ethernet addresses

### PR DESCRIPTION
**Pull request by astro**

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 482167e has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 482167e4cf5795cbb5ba4e4ce92f243f905689d7 with merge 9e4d2bea8f0931e8c87ae611197fe90b2bf02f58...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/348035790?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 9e4d2bea8f0931e8c87ae611197fe90b2bf02f58 to master...

**Pull request closed without merging**
