### PR TITLE
Implement peek functions for UDP sockets

### PR DESCRIPTION
**Pull request by pothos**
This needed a peek function for the packet buffer.

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 6bc1496 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 6bc1496f2a1d4ed95f27b0d32033199dd4c01355 with merge 0588101384e91ea23c4e8820e270a8d6c823730a...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/499382623?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 0588101384e91ea23c4e8820e270a8d6c823730a to master...

**Pull request closed without merging**
