### PR TITLE
Implement Hash for SocketHandle

### PR DESCRIPTION
**Pull request by tomaka**

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit a138c0d has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit a138c0d8d785d8c60f7e8d0a778683402957415b with merge 2f80e1ac6a926575455810678bf5cef5a56e43ca...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/628459010?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 2f80e1ac6a926575455810678bf5cef5a56e43ca to master...

**Pull request closed without merging**
