### PR TITLE
Only change the assembler state on success

### PR DESCRIPTION
**Pull request by pothos**
The current hole was always shrinked even if the
packet assembler rejected adding a packet due to
not being able to insert a new hole.

Shrink only after a new hole was added.
Shrinking before or after does not make a difference
because offset + size < hole_size and thus
contigs[index] is not empty, passing the
debug_assert in add_contig_at.

https://github.com/m-labs/smoltcp/issues/261

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+
Thanks!

**Comment by m-labs-homu** [comment]
:pushpin: Commit 9ccf18e has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 9ccf18e0b61efc49480aa538495a7e746bed1d16 with merge 68869defc79e7bce8d4a7e09aa7981ccb7cc4a44...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/431871967?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 68869defc79e7bce8d4a7e09aa7981ccb7cc4a44 to master...

**Pull request closed without merging**
