### PR TITLE
Add iter_data() to Assembler

### PR DESCRIPTION
**Pull request by jhwgh1968**
This is part of the groundwork for #256. I wanted to open a separate PR for this so that @whitequark could provide comments on the approach I am taking.

This adds a new method ``iter_data()`` to the Assembler. It performs the calculation of data ranges that are stored given a byte offset.

### CODE REVIEW

**Comment by jhwgh1968** [comment]
Wow, @whitequark, you were quick! I tried to sneak in one last-minute commit amend, but you'd already approved it by then. (Just a documentation tweak, which turned out not to be helpful.)

I have reverted to the version the Homu bot approved, hopefully that will unstick the build.

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit a6d364a has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit a6d364a2ccfdc59d5c4e644b6fe49c01c51b8215 with merge 2acd13fe8b54ccac4f4b62158845c767b47f4b49...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/423248510?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 2acd13fe8b54ccac4f4b62158845c767b47f4b49 to master...

**Pull request closed without merging**
