### PR TITLE
wire: Add the FailureType for IPv6 ext hdr options

### PR DESCRIPTION
**Pull request by dlrobertson**
Add the FailureType enumeration that can be acquired from a IPv6
extension header option which determines the required action if the
extension header option type is not known or is not supported.

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit d82ad7b has been approved by `whitequark`

**Comment by dlrobertson** [comment]
I think I pushed an update after your approval. Just changed the display text for the `FailureType`.

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 2854e2d has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 2854e2d8583fc9c713d2c680533c5073bd533ff4 with merge bf1d5ed21126dd8e3b94b8d871fc33293f1da156...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/376822617?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing bf1d5ed21126dd8e3b94b8d871fc33293f1da156 to master...

**Comment by whitequark** [comment]
@dlrobertson By the way, you are already in the reviewers list.

**Pull request closed without merging**
