### PR TITLE
Fix the ipv6 option structure

### PR DESCRIPTION
**Pull request by dlrobertson**
The IPv6 Option representation layer structure includes the type value
as the raw `u8`. This should be stored as the `Type` enum.

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit fed0600 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit fed0600233647ecb37b4189c2cae3c737bb794e5 with merge b3651cc5b8d22aa1a8cd957ec301a3dec317ebff...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/388534257?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing b3651cc5b8d22aa1a8cd957ec301a3dec317ebff to master...

**Pull request closed without merging**
