### PR TITLE
Log and print poll errors instead of crashing the server

### LINKED ISSUE #227: Server example broken
Commit https://github.com/m-labs/smoltcp/commit/2363f97834b3d529c6344f1840ab001645e853d2 broke server example:

```
$ cargo run --example server tap1
warning: unused manifest key: package.autoexamples
   Compiling smoltcp v0.4.0 (file:///home/michal/Workspace/rust_projects/smoltcp)
    Finished dev [unoptimized + debuginfo] target(s) in 5.66 secs
     Running `target/debug/examples/server tap1`
[1528220661.171s] (socket::set): [0]: adding
[1528220661.171s] (socket::set): [1]: adding
[1528220661.171s] (socket::set): [2]: adding
[1528220661.171s] (socket::set): [3]: adding
[1528220661.172s] (socket::set): [4]: adding
[1528220661.172s] (socket::tcp): #1:*:6969: state=CLOSED=>LISTEN
[1528220661.172s] (socket::tcp): #2:*:6970: state=CLOSED=>LISTEN
[1528220661.172s] (socket::tcp): #3:*:6971: state=CLOSED=>LISTEN
[1528220661.172s] (socket::tcp): #4:*:6972: state=CLOSED=>LISTEN
[1528220661.183s] <- EthernetII src=5e-13-5d-a6-c5-f2 dst=33-33-00-00-00-16 type=IPv6
                \ IPv6 src=fe80::5c13:5dff:fea6:c5f2 dst=ff02::16 nxt_hdr=Hop-by-Hop hop_limit=1
[1528220661.183s] (iface::neighbor): filled fe80::5c13:5dff:fea6:c5f2 => 5e-13-5d-a6-c5-f2 (was empty)
[1528220661.183s] (iface::ethernet): cannot process ingress packet: unrecognized packet
[1528220661.183s] (iface::ethernet): packet dump follows:
EthernetII src=5e-13-5d-a6-c5-f2 dst=33-33-00-00-00-16 type=IPv6
\ IPv6 src=fe80::5c13:5dff:fea6:c5f2 dst=ff02::16 nxt_hdr=Hop-by-Hop hop_limit=1
thread 'main' panicked at 'poll error: Unrecognized', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The correct behavior (with commit https://github.com/m-labs/smoltcp/commit/dd80b22a98fd60da9602779295b073def3b9ecf3 ) is:

```
$ cargo run --example server tap1
warning: unused manifest key: package.autoexamples
   Compiling smoltcp v0.4.0 (file:///home/michal/Workspace/rust_projects/smoltcp)
    Finished dev [unoptimized + debuginfo] target(s) in 5.76 secs
     Running `target/debug/examples/server tap1`
[1528220498.560s] (socket::set): [0]: adding
[1528220498.560s] (socket::set): [1]: adding
[1528220498.560s] (socket::set): [2]: adding
[1528220498.560s] (socket::set): [3]: adding
[1528220498.560s] (socket::set): [4]: adding
[1528220498.560s] (socket::tcp): #1:*:6969: state=CLOSED=>LISTEN
[1528220498.560s] (socket::tcp): #2:*:6970: state=CLOSED=>LISTEN
[1528220498.560s] (socket::tcp): #3:*:6971: state=CLOSED=>LISTEN
[1528220498.560s] (socket::tcp): #4:*:6972: state=CLOSED=>LISTEN
[1528220498.571s] <- EthernetII src=5e-13-5d-a6-c5-f2 dst=33-33-00-00-00-16 type=IPv6
                \ IPv6 src=fe80::5c13:5dff:fea6:c5f2 dst=ff02::16 nxt_hdr=Hop-by-Hop hop_limit=1
[1528220498.571s] (iface::neighbor): filled fe80::5c13:5dff:fea6:c5f2 => 5e-13-5d-a6-c5-f2 (was empty)
[1528220498.667s] <- EthernetII src=5e-13-5d-a6-c5-f2 dst=33-33-00-00-00-16 type=IPv6
                \ IPv6 src=fe80::5c13:5dff:fea6:c5f2 dst=ff02::16 nxt_hdr=Hop-by-Hop hop_limit=1
```

### PR DESCRIPTION
**Pull request by podhrmic**
Fixes #227

### CODE REVIEW

**Comment by dlrobertson** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 9b0041b has been approved by `dlrobertson`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 9b0041bc8350ad7b4e8e86549b511dfabe13fec9 with merge 917f259baecaa0df829a8cee7be2a4dcee22eab7...

**Comment by dlrobertson** [comment]
Sorry, I guess homu doesn't respond to reviews

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/388513812?utm_source=github_status&utm_medium=notification)
Approved by: dlrobertson
Pushing 917f259baecaa0df829a8cee7be2a4dcee22eab7 to master...

**Comment by whitequark** [comment]
Can you do this for all other examples as well?

**Comment by podhrmic** [comment]
I will put in on my todo list.

**Pull request closed without merging**
