### PR TITLE
Imp `From` trait on EthernetAddress

### PR DESCRIPTION
**Pull request by LuoZijun**

### CODE REVIEW

**Comment by whitequark** [comment]
Why?

**Comment by LuoZijun** [comment]
@whitequark 

just for friendly api.

and i also add `Hash` trait on `EthernetAddress` .

**Comment by whitequark** [comment]
So what's "friendly" about it? I don't see the use case.

**Comment by LuoZijun** [comment]
@whitequark 

```rust
let hwaddr = EthernetAddress::from([1,2,3,44,5,6]);

```

**Comment by whitequark** [comment]
> let hwaddr = EthernetAddress::from([1,2,3,44,5,6]);

This is longer than using the constructor directly:

    let hwaddr = EthernetAddress([1,2,3,4,5,6]);

**Comment by LuoZijun** [comment]
yeah, got it.

now just add `Hash` trait.

**Pull request merged**
