### PR TITLE
Move more iface tests to test ipv6

### PR DESCRIPTION
**Pull request by dlrobertson**
I used `cfg` to use IPv6 if IPv6 is available and IPv4 otherwise. We could instead test both, with a `test_ipv4` test module and `test_ipv6` test module. Would that be preferred?

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 9a56b3d has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 9a56b3d4e9df9b706347431087934becfe0211f8 with merge 43a049382b12a4c9131637b753f58b53a87d29ad...

**Comment by m-labs-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/395998727?utm_source=github_status&utm_medium=notification)

**Comment by whitequark** [comment]
@m-labs-homu retry

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/396007572?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 94d7338aed6d4b5157d328915b5ac94236fc6427 to master...

**Pull request closed without merging**
