### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by dlrobertson**
nit: remove some trailing whitespace.

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 3021af8 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 3021af8f221dc1ec505f38ed9d71bd6abbcb43db with merge c425efa1ba6b1188660f396886e9d3017207bc5f...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/346329662?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing c425efa1ba6b1188660f396886e9d3017207bc5f to master...

**Pull request closed without merging**
