### PR TITLE
Improve TimeExceeded and ParamProblem support

### PR DESCRIPTION
**Pull request by dlrobertson**
- Improve TimeExceeded support
   - Add support for message codes
   - Add the TimeExceeded enum type
 - Improve ParamProblem support
   - Add support for message codes
   - Add the ParamProblem enem type

Merge before: #142

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit e5dcaec has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit e5dcaecefd31232bb66b31f9919b9a924ee27a8c with merge 7b5971ca244d4bbe3c7835dbcc72ace0c99f07b4...

**Comment by dlrobertson** [comment]
+1 for homu!!!

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/337585216?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 7b5971ca244d4bbe3c7835dbcc72ace0c99f07b4 to master...

**Pull request closed without merging**
