### PR TITLE
Add support for rebinding to DHCP implementation

### PR DESCRIPTION
**Pull request by JarredAllen**
The current DHCP implementation does not include the REBINDING state as detailed in the spec. I propose modifying the REBINDING state to send request packets until the REBINDING time begins, and then broadcast request packets once the REBINDING time begins.

I added assertions for broadcast request packets to the existing unit tests, which pass. I also validated on my setup that it sent a broadcast request at the T2 time my DHCP server sends. I think this should be sufficient validation, but I can provide more if requested.

There were a couple edge cases of the DHCP protocol pertaining to this change for which I couldn't find a specification in the standards. I documented the decisions I made in those cases, but I'm not attached to what I did (my setup hits none of them) so I can change it to something else if you prefer.

### CODE REVIEW

**Comment by JarredAllen** [comment]
Hey, are there any updates on this? Thanks for this library, it's great to use and really helpful! But I've been hitting issues caused by this part of the DHCP spec being missing, so I'd love it if we could get this PR in soon. Thanks!

**Comment by JarredAllen** [comment]
(force push done to rebase onto current changes)

**Comment by thvdveld** [comment]
@Dirbaio this looks good to me.

**Review by Dirbaio — APPROVED** [review]
Thank you!

bors r+

**Pull request merged**
