### PR TITLE
Allow receiving broadcast packets in UDP

### PR DESCRIPTION
**Pull request by jackpot51**
This allows the reception of UDP broadcast packets. They will fall through to the process_udp function. The tcp and icmp functions also receive potential broadcast packets, but they should already be discarded.

### CODE REVIEW

**Comment by dlrobertson** [comment]
The destination address is not checked to see if it is the broadcast address before sending ICMP error responses currently (RFC 1122 § 3.2.2). Currently this conditional is the only thing keeping us from causing a broadcast storm due to a weird broadcast packet. The specific panic is [here](https://github.com/m-labs/smoltcp/blob/master/src/iface/ethernet.rs#L369), and is due to the packet created for the [`no_icmp_to_broadcast`](https://github.com/m-labs/smoltcp/blob/master/src/iface/ethernet.rs#L675-L707) test having no payload.

**Comment by whitequark** [comment]
@dlrobertson Wow, your tests already paid off. Thanks a lot!

**Comment by jackpot51** [comment]
@whitequark, I believe @dlrobertson is working on a fix, to prevent the ICMP error message from being sent

**Comment by dlrobertson** [comment]
After a rebase, tests should pass here.

**Comment by whitequark** [comment]
@jackpot51 Can you rebase?

**Comment by jackpot51** [comment]
Yep, will do

**Comment by jackpot51** [comment]
@whitequark it is done

**Comment by whitequark** [comment]
Any chance you can write a test for this?

**Comment by jackpot51** [comment]
Sure!

**Comment by jackpot51** [comment]
@whitequark I do not see any current tests for UDP in the ethernet interface, am I mistaken?

**Comment by dlrobertson** [comment]
@jackpot51 https://github.com/m-labs/smoltcp/blob/master/src/iface/ethernet.rs#L828-L911 is an example of a test in the ethernet interface for UDP. Essentially you could do the same thing as the second half of that test, but add a socket to the socket set that is listening to the port of interest.

**Comment by jackpot51** [comment]
Ok, cool

**Comment by whitequark** [comment]
@jackpot51 ping?

**Comment by jackpot51** [comment]
Sorry @whitequark, I have been busy porting cargo.

**Comment by dlrobertson** [comment]
I added tests with redox-os/smoltcp#1

**Comment by jackpot51** [comment]
@whitequark the tests from @dlrobertson are now merged

**Pull request merged**
