### PR TITLE
Add fuzz tests for 6LoWPAN_IPHC and 6LoWPAN_UDP

### PR DESCRIPTION
**Pull request by thvdveld**
(Some more fuzzing!!)

Adding fuzz tests for 6LoWPAN_IPHC and 6LoWPAN_UDP.
Some bugs were found.

Ran for 10 minutes.

### CODE REVIEW

**Review by Dirbaio — APPROVED** [review]
Thank you!!

bors r+

**Comment by Dirbaio** [comment]
oh, there's some issue with tests

bors cancel
bors d+

**Comment by thvdveld** [comment]
Yeah, the error from the test is:
`error: could not download file from 'https://static.rust-lang.org/rustup/release-stable.toml' to '/tmp/rustup-updateHrmg5v/release-stable.toml': failed to make network request: error sending request for url (https://static.rust-lang.org/rustup/release-stable.toml): connection error: Connection reset by peer (os error 104): connection error: Connection reset by peer (os error 104): Connection reset by peer (os error 104)`.

That was the same problem with the other PR, not sure how to fix that :stuck_out_tongue:

(Or is it another one that I looked over?)

**Comment by Dirbaio** [comment]
oh, that's just an annoying spurious failure. It works if you retry.  I've restarted CI.

**Pull request merged**
