### PR TITLE
Subnet broadcasts

### PR DESCRIPTION
**Pull request by MabezDev**
I previously opened this before, but I think it got lost the repo ownership changes.

Currently smoltcp only responds to physical layer broadcasts (255.255.255.255), this PR enables the interface to respond to subnet broadcasts, as discussed in https://tools.ietf.org/html/rfc917 chapter 8.

## Questions

- Should this check be applied to all `ip_addrs` associated with the iface?

### CODE REVIEW

**Comment by MabezDev** [comment]
Seems like the travis errors are unrelated, as they fail on current master too?

**Comment by whitequark** [comment]
No idea what happened with tests, shouldn't that be impossible with protected branches, anyway?

**Comment by Dirbaio** [comment]
Yes, master is broken, with ~~both stable and~~ nightly. EDIT see #378 What's weird is that commits that Travis previously said passed tests are now not passing.

**Comment by whitequark** [comment]
Should probably be squashed, looks reasonable otherwise.

**Review by Dirbaio — CHANGES_REQUESTED** [review]
> Should this check be applied to all ip_addrs associated with the iface?

I'd say yes. We process unicast packets for all our IPs, IMO it's quite strange that we only process broadcast packets for the first one.

Looks great otherwise! :)

**Review by Dirbaio — APPROVED** [review]
Looks great now that it checks all our addrs!

Commits got somehow duplicated when merging, can you rebase on top of master?

**Comment by MabezDev** [comment]
> Looks great now that it checks all our addrs!
> 
> Commits got somehow duplicated when merging, can you rebase on top of master?

Will do, some tests are still failing so I'll fix those first and then squash.

**Comment by MabezDev** [comment]
Should be good to go :)

**Comment by Dirbaio** [comment]
There's still a clippy failure :(

**Comment by MabezDev** [comment]
Whoops, must have missed that! Should be fixed now, sorry about that :)

**Comment by MabezDev** [comment]
Fairly minor change, but I realised only ipv4 has the concept of broadcasts, so I removed a pointless match, and instead just pass the ip directly.

**Comment by Dirbaio** [comment]
Awesome! Thank you!

**Pull request merged**
