### PR TITLE
Add MLDv2 packet parsing support to wire

### PR DESCRIPTION
**Pull request by dlrobertson**
Add the basics for parsing MLDv2 packets with the Icmpv6Packet structure
in the wire module.

### CODE REVIEW

**Comment by dlrobertson** [comment]
To make the PR a bit smaller I only included packet parsing support in this PR. I'll submit a follow-up with a `Repr`.

**Comment by whitequark** [comment]
Thanks for another high-quality contribution!
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 354b3c4 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 354b3c4b18de1f5c6c3a959c9574db3b0f1b163d with merge 78651bb5696189fd36cf3c6fa3abeebe586c42bc...

**Comment by m-labs-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/395645221?utm_source=github_status&utm_medium=notification)

**Comment by whitequark** [comment]
@m-labs-homu retry

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 354b3c4b18de1f5c6c3a959c9574db3b0f1b163d with merge f4c76b2a5722e303fa8bd7ca57f826ff3cfa65e6...

**Comment by m-labs-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/395706134?utm_source=github_status&utm_medium=notification)

**Comment by whitequark** [comment]
@m-labs-homu retry

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 354b3c4b18de1f5c6c3a959c9574db3b0f1b163d with merge 48bc838b69a1168bc0f57c521e2879b0de44a4f8...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/395708809?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 48bc838b69a1168bc0f57c521e2879b0de44a4f8 to master...

**Pull request closed without merging**
