### PR TITLE
Fixes all the clippy lints

### PR DESCRIPTION
**Pull request by thvdveld**

### CODE REVIEW

**Comment by thvdveld** [comment]
Damn, I pulled from the wrong master branch...

**Comment by thvdveld** [comment]
Now from the correct master branch.

**Comment by Dirbaio** [comment]
Thanks for this, PR looks great! 

CI is broken because bitflags 1.3 bumped MSRV to 1.46. I'll bump ours

**Review by Dirbaio — APPROVED** [review]
MSRV bumped, should work now

**Pull request merged**
