### PR TITLE
Increase number of assembler gaps to 32

### PR DESCRIPTION
**Pull request by pothos**
This is just a proposal, maybe a build feature is prefered? If yes, what values should be included?
Or should we rather introduce a decoupled scheme as established with the socket buffers?

### CODE REVIEW

**Comment by pothos** [comment]
Rather an API change for Assembler and ManagedSlice or really just a Box for std/alloc?

**Comment by pothos** [comment]
Seems that `cargo test` has a bug in evaluating the cfg macros: There is a compile error because some definitions are compiled with cfg std and some without!?

**Comment by pothos** [comment]
Yes, but I'm surprised about the combination of code with differently evaluated cfg parts.

**Comment by pothos** [comment]
Got my mistake, I didn't see that the same lines also were in `mod test`… and got confused by the warning.

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 2f9a5ba has been approved by `whitequark`

**Comment by whitequark** [comment]
@pothos Sorry, I did not notice that you updated the branch.

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 2f9a5babd45458b254eff0d31054d401d886f2e0 with merge ef014b118b19d2c4e9218be6ab52ffe4c2aecff3...

**Pull request closed without merging**
