### PR TITLE
impl `AsRef<[u8]>` for packet types

### LINKED ISSUE #157: Implement `As{Ref,Mut}<[u8]>` for packet types.
I can already call `.into_inner()` to extract the buffer from an `Ipv4Packet`/`EthernetFrame` etc. It should be possible to get a reference to the buffer without consuming the packet object.

### PR DESCRIPTION
**Pull request by canndrew**
Fixes #157

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 227fab8 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 227fab85e3bacc8df3045da865f0155877080946 with merge fb96b3cdc1ba85dbb2cfbda1f1ae9cb10768980d...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/338886732?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing fb96b3cdc1ba85dbb2cfbda1f1ae9cb10768980d to master...

**Pull request closed without merging**
