### PR TITLE
Improve the Iterator for IPv6 options

### PR DESCRIPTION
**Pull request by dlrobertson**
- Add a helper function for returning an error in the implementation of
   next
 - Add an assert in Ipv6OptionsIterator::new that ensures that an
   iterator is not created with a length field larger than that of the
   data buffer we're iterating over.

### CODE REVIEW

**Comment by dlrobertson** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit fc33355 has been approved by `dlrobertson`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit fc333555ad305ad68412145884af35942f4a1bcb with merge d6fd91cc59d08fba50a609351c2e40d7da919fdd...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/388974208?utm_source=github_status&utm_medium=notification)
Approved by: dlrobertson
Pushing d6fd91cc59d08fba50a609351c2e40d7da919fdd to master...

**Pull request closed without merging**
