### PR TITLE
Fix packet buffer enqueue logic error

### PR DESCRIPTION
**Pull request by dlrobertson**
The size of the contiguous window should be prioritized over the size of
the contiguous window if padding were added.

For example, given the following packet buffer:
```
  1   2     3
|---|----|------|
```

If 2 is used and 1 and 3 are empty, enqueing a buffer of size 4 should
be placed in contiguous window 3 and the size of 1 should not cause
any issues in `enqueue`.

Fixes: #245

### CODE REVIEW

**Comment by birkenfeld** [comment]
Perfect, thanks!

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 435169f has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 435169fe9990ed2e54c66539c73769160af06017 with merge 682fc3078229a4fc06b5f021af058c45b9f3bc02...

**Pull request closed without merging**
