### PR TITLE
Fix server example

### PR DESCRIPTION
**Pull request by dlrobertson**
Make the IPv6 address used in the server example the same as the IPv6
address used in the others.

### CODE REVIEW

**Comment by dlrobertson** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 968cc04 has been approved by `dlrobertson`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 968cc040df53c6cf419ca5bb48329f5fe8caf6f0 with merge 602724b2858e11d664bc686abed0cdebd1d97696...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/380868591?utm_source=github_status&utm_medium=notification)
Approved by: dlrobertson
Pushing 602724b2858e11d664bc686abed0cdebd1d97696 to master...

**Pull request closed without merging**
