### PR TITLE
Add has_solicited_node to EthernetInterface

### PR DESCRIPTION
**Pull request by dlrobertson**
- Add a function to EthernetInterface useful for determining if a
   received packet with the source address being a solicited node
   address is the solicited node address for an IPv6 address assigned
   to the interface.
 - Add SOLICITED_NODES_PREFIX to Ipv6Cidr
 - Fix some nits

### CODE REVIEW

**Comment by dlrobertson** [comment]
Adding IPv6 address resolution to `EthernetInterface` will take quite a bit of work. I'll try my best to break it down into small bite-sized chunks like this, when possible.

**Comment by whitequark** [comment]
@m-labs-homu r+
@dlrobertson thanks!

**Comment by m-labs-homu** [comment]
:pushpin: Commit 5cb8717 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 5cb8717fd2caa17d9ed853bc212a32a5bf141b77 with merge 89999a69812659e5241f8561d1ecb3fd1c949a9f...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/348720074?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 89999a69812659e5241f8561d1ecb3fd1c949a9f to master...

**Pull request closed without merging**
