### PR TITLE
Suppress ICMP error replies for packets that are accepted by raw sockets

### PR DESCRIPTION
**Pull request by astro**
Singled out from #186

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 4fa66c9 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 4fa66c9e98f6ebcd6280760bf89a9ee686f24ee3 with merge f56666a26722c4f4f962937119d71792b51c396e...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/526711242?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing f56666a26722c4f4f962937119d71792b51c396e to master...

**Pull request closed without merging**
