### PR TITLE
Allow broadcast/multicast traffic to UDP sockets

### PR DESCRIPTION
**Pull request by astro**
The path for broadcast seemed prepared, therefore adding multicast into it seemed logical.

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 7a26517 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 7a26517b1fac950482f410d8810da078b6d7fc0c with merge 2d2b90fd0469c8de4c3469aca11b763874891b71...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/348448828?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 2d2b90fd0469c8de4c3469aca11b763874891b71 to master...

**Pull request closed without merging**
