### PR TITLE
Implement Any-IP feature

### PR DESCRIPTION
**Pull request by cbranch**
Any-IP is the capability to accept packets locally even when the
destination address is not configured on any interface. This lets
a service bind to an entire subnet of addresses and is particularly
useful in anycast deployments.

See also:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4465b469008bc03b98a1b8df4e9ae501b6c69d4b
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ab79ad14a2d51e95f0ac3cef7cd116a57089ba82

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 4053e27 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 4053e27f26abcc4bde7257c33cc9d033282efb0b with merge a1d0e0c2af00ef56ea48663ef751cb122c0ad08f...

**Comment by m-labs-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/496009414?utm_source=github_status&utm_medium=notification)

**Comment by cbranch** [comment]
Ah,  it looks like I forgot to account for all the feature permutations (not really surprised) - looking into it.

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by dlrobertson** [comment]
:( looks like homu is rebelling

**Comment by whitequark** [comment]
@m-labs-homu retry

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 824bc13 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 824bc13fe78cfa0498cfffedb6d1a40c7cfc4611 with merge 6793792b02d7da436d08b6ab6eecf25c171eb3b5...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/508107503?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 6793792b02d7da436d08b6ab6eecf25c171eb3b5 to master...

**Pull request closed without merging**
