### PR TITLE
Add Repr support for NDISC packets

### PR DESCRIPTION
**Pull request by dlrobertson**
Add Representation layer support for NDISC packets.

### CODE REVIEW

**Comment by dlrobertson** [comment]
After this we can start on address resolution on IPv6!

**Comment by whitequark** [comment]
Thanks for the PR! Since `icmpv6.rs` contains only "base" ICMPv6 packets right now, with `ndisc.rs` containing NDISC packet code, do you think you can move out `Repr` (which of course cannot be easily split) into `icmpv6repr.rs`?

**Comment by dlrobertson** [comment]
You mean have a separate module with all of `Icmpv6Repr` in it or a separate module with the NDISC variants.

**Comment by whitequark** [comment]
The former--I don't think the latter is possible in Rust.

**Comment by whitequark** [comment]
Actually, on second thought, that will cause issues with tests. Let me think a bit more about the best course of action here.

**Comment by dlrobertson** [comment]
What about adding a `Ndisc(NdiscRepr)` variant to `Icmpv6Repr`?

**Comment by whitequark** [comment]
Let's do that.

**Comment by dlrobertson** [comment]
:+1:

**Comment by dlrobertson** [comment]
Updated to use a `Ndisc(NdiscRepr<'a>)` variant.

**Comment by whitequark** [comment]
Thanks! This is very nice.

**Pull request merged**
