### PR TITLE
[Breaking] Update to bitflags 2.x

### PR DESCRIPTION
**Pull request by GnomedDev**
Gets rid of this old duplicate dependency in my dep tree.

### CODE REVIEW

**Comment by whitequark** [comment]
Does defmt no longer provide a derive macro?

**Comment by GnomedDev** [comment]
bitflags 2.x swapped the internals of each bitflag type from just a newtype around the integer to a newtype around a private newtype. This means that derives that just try to touch the inner value can't work, hence having to make our own macro to implement formatting the bits.

**Comment by whitequark** [comment]
Thanks. @Dirbaio what do you think about the macro? it feels a bit heavyweight but maybe that's just me.

**Comment by GnomedDev** [comment]
I can change the macro to be separate and not replace the bitflags invocation, if that would be preferred, as in
```rust
bitflags::bitflags! {
	pub struct Flags: u8 {
		...
	}
}

impl_bitflags_defmt!(Flags);
```

**Pull request closed without merging**
