### PR TITLE
Mac

### PR DESCRIPTION
**Pull request by kornelski**
edit: oops, I've meant to make PR for a different fork :)

### CODE REVIEW

**Comment by whitequark** [comment]
@kornelski Which fork?

**Comment by kornelski** [comment]
https://github.com/cbranch/smoltcp

**Comment by pothos** [comment]
Nice to see some work is done and even in the open. @cbranch and @kornelski, maybe you can give some context? Do you want to upstream the patches here someday or mind if others are doing it since you kept the license?

**Comment by whitequark** [comment]
I am guessing the problem is that I don't have enough review bandwidth.

**Comment by pothos** [comment]
That's probably one factor in general but the current situation is not terribly bad and could be much worse – you did quite well ;)

**Pull request closed without merging**
