### PR TITLE
Mention that Probing Zero Windows is not implemented for TCP

### PR DESCRIPTION
**Pull request by pothos**
Discussed in #199

### CODE REVIEW

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit ab2ef05 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit ab2ef054a1102018dd17258fda8e8ae952c5c9b3 with merge 880fb73d544f8a158996f04c7417d9aa092d2b31...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/376006755?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 880fb73d544f8a158996f04c7417d9aa092d2b31 to master...

**Pull request closed without merging**
