### PR TITLE
TCP emit panic: Proper calculation of TCP header length

### PR DESCRIPTION
**Pull request by pothos**
Currently master panics when emitting TCP with the MSS and Window Scale options set.

Requirement to solve the root cause:
The presence of TCP options will only increase
the header length to muliples of 4. The added
padding consists of zeros.

This also fixes an emit panic when the Window
Scale and MSS options result in a length of 27
which then gets floored to 24 when applied to
the header.

### CODE REVIEW

**Comment by whitequark** [comment]
The CI is failing: https://travis-ci.org/m-labs/smoltcp/jobs/397705601#L517

**Comment by pothos** [comment]
Have added the feature guard to the test.

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit af737ba has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit af737baa4d005a1cedadce49b0a7d6a84246f4af with merge 4a8242a1fe87a33ad23c15fb46b0365d9f73ff56...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/397753505?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 4a8242a1fe87a33ad23c15fb46b0365d9f73ff56 to master...

**Pull request closed without merging**
