### PR TITLE
Interface `ip_addrs` field from slice to `heapless::Vec`

### PR DESCRIPTION
**Pull request by davidedellagiustina**
As stated in the title.
One cargo test is still failing, needs to be looked into.

Moreover, for now the `heapless::Vec` used is fixed-size.

### CODE REVIEW

**Comment by MabezDev** [comment]
Is there any particular reason you need/want this? What's wrong with the `ManagedSlice` method?

**Comment by Dirbaio** [comment]
It's to fix #458 and some cases of #466.

The problem with `ManagedSlice` is that in the borrowed case it is fixed length, so you can't dynamically add/remove IPs. If you want to have "no IP" (for example for when DHCP is not up yet) you have to change it to `0.0.0.0` instead. This causes smoltcp to transmit garbage packets with source IP `0.0.0.0`, because it treats it like any other IP in the egress code.

The alternative would be to change egress to treat `0.0.0.0` as "not a real IP", but that's an ungly workaround. The root issue is that the IP list should be variable length even in nostd.

(This probably applies to other ManagedSlice's in Interface as well, these'd be better off as `Vec`s. For example the routes and neighbor cache. We'll change them in future PRs)

**Comment by davidedellagiustina** [comment]
Exactly what @Dirbaio said. I'm still trying to understand how to fix the failing test though.

**Comment by MabezDev** [comment]
Thanks! I'm pretty sure smoltcp & managed predate heapless so It'll be nice to eventually use heapless instead and phase out managed. I'm sure it would help for https://github.com/smoltcp-rs/smoltcp/issues/655.

**Comment by davidedellagiustina** [comment]
Before forgetting, there is also an additional point that I briefly discussed with @Dirbaio in private: for now, I used a hardcoded constant as the maximum size of the `ip_addrs` vector, but this might restrict some use cases. We agreed on the fact that using a generic parameter would pollute the API in an undesirable way, and probably the best way would be adding some cargo features to allow for different (though predefined) sizes for such vector. But any further idea is welcome.

**Review by Dirbaio — APPROVED** [review]
LGTM, thank you!

Yes, we can work on making the max count customizable in the future.

**Pull request merged**
