### PR TITLE
Fix code style nits

### PR DESCRIPTION
**Pull request by dlrobertson**
Fixing very minor nits I noticed while doing some other work.

### CODE REVIEW

**Comment by dlrobertson** [comment]
r? @whitequark 

`unused_mut_ref` from clippy.

**Comment by whitequark** [comment]
@m-labs-homu r+

**Comment by m-labs-homu** [comment]
:pushpin: Commit 107cc83 has been approved by `whitequark`

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 107cc832cf76c9a905c3f3432b6ffd695e93aa33 with merge 605c5d657f21ddba3653f471901bd88739c82fc8...

**Comment by dlrobertson** [comment]
@m-labs-homu retry

`auto` test merge passed 5 hrs ago.

**Comment by m-labs-homu** [comment]
:hourglass: Testing commit 107cc832cf76c9a905c3f3432b6ffd695e93aa33 with merge 8d2a20362ec230f3038639faa7cc2fd39999ab11...

**Comment by m-labs-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/m-labs/smoltcp/builds/397347330?utm_source=github_status&utm_medium=notification)
Approved by: whitequark
Pushing 8d2a20362ec230f3038639faa7cc2fd39999ab11 to master...

**Pull request closed without merging**
